function []=mapmake(bounds,filename)
    f=fopen('C:\Maperitive\Scripts\exporting.mscript','w');
    fprintf(f,['use-ruleset alias=default\n' ...
                'add-web-map provider="stamen.toner"\n' ...
                'set-geo-bounds %f, %f, %f, %f' ...
                'zoom-bounds' ...
                'export-bitmap %s'],...
                bounds(1),bounds(2),bounds(3),bounds(4),filename);
    fclose(f);
    system(['C:/Maperitive/Maperitive.Console.exe ' ...
        '-viewheight=2800 -viewwidth=2240 Scripts/exporting.mscript']);
end